### ISSUE TITLE
Docblocks

### ISSUE THREAD

**Issue by sagikazarmark** [florianv/business#10]
I noticed a few minor things related to docblocks:

- Integers are represented as `integer` instead of `int` (which is good IMO), but booleans are `bool`.
- There are no `@throws` docblocks

**Comment by florianv** [comment]
> Integers are represented as integer instead of int (which is good IMO), but booleans are bool

It's an issue indeed, it should be `int` instead of `integer` to match HHVM and PHP7 type names

> There are no @throws docblocks

They need to be added (will do it once I have time)
