### ISSUE TITLE
Working day interval manipulation

### ISSUE THREAD

**Issue by pyrech** [florianv/business#13]
Nice work on this project. :)

Business is close to what I need (manipulate a list of working days, excluding public holiday) but for my use case, it lacks of interval operations:

I need to do something like: 
```php
// Get the third working days starting from now
$date = $business->add(new \DateTime(), 3);
```

So I just wonder if this feature could enter in the scope of business?

**Comment by florianv** [comment]
Thanks :)

To get the third business day starting from now (excluding it) you can do something like:

```php
$n = 3;
$date = new \DateTime();

for ($i = 0; $i < $n; $i++) {
    $date->modify('+1 day');
    $date = $business->closest($date);
}
```

**Comment by pyrech** [comment]
Ahah, awesome! Thanks :) Let's use business \o/
