### ISSUE TITLE
Holidays::addHolidays is private

### ISSUE THREAD

**Issue by bendavies** [florianv/business#15]
Hi Florian!

Thanks for a great library!
Can I ask why `Holidays::addHolidays` is private? I have a use case where i want to dynamically add holidays *after* the `Business` object has been instantiated, so I'm having resort to trickery to access `Holidays::addHolidays` at the moment.

Would you consider making that method public?

Thanks!

**Comment by florianv** [comment]
Hey Ben,

thanks for your feedback!

I don't see any issue making these methods public.

**Comment by bendavies** [comment]
Thanks, I'll submit a PR when i get some time.

**Comment by florianv** [comment]
Ok thank you!

I think we can put `Holidays::addHoliday` public as well.
