### ISSUE TITLE
The opening time "xx:xx" must be before the closing time "xx:xx"

### ISSUE THREAD

**Issue by krombox** [florianv/business#17]
`new Day(Days::TUESDAY, [['9 PM', '5 AM']])`
 
Fatal error: Uncaught exception 'InvalidArgumentException' with message 'The opening time "21:00" must be before the closing time "05:00".'
I think in this case better not to throw an exception. Some night-clubs are open late and close next-day(like 5am)

**Comment by florianv** [comment]
5AM is not Thursday anymore so your day definition is incorrect. The correct definition is

```
new Day(Days::TUESDAY, [['9 PM', '12 PM']])
new Day(Days::WEDNESDAY, [['12 PM', '5AM']])
```

**Comment by eabay** [comment]
Thank you for this great library!

I had the same issue although I'm doing what you suggested.

```php
new Day(Days::TUESDAY, [["10:00", "00:00"]])
new Day(Days::WEDNESDAY, [["10:00", "00:00"]])
```

And got:
```
InvalidArgumentException in TimeInterval.php line 38:
The opening time "10:00:00" must be before the closing time "00:00:00".
```

I should be doing something wrong...

**Comment by florianv** [comment]
Hey,

thank you :)

I think you have to setup your times like so as `00:00` is considered to be the next day

```php
new Day(Days::TUESDAY, [["10:00", "23:59:59"]])
new Day(Days::WEDNESDAY, [["10:00", "23:59:59"]])
```

**Comment by eabay** [comment]
And thanks for the fast reply :)

This is exactly what I am doing right now but it doesn't feel right while working with a reservation system which has time slots to be booked and I have to use workarounds for the last slot, 23:00-00:00.

I wish 24:00 would programatically be considered within the day instead of next day :)
