### ISSUE TITLE
Installing through composer

### ISSUE THREAD

**Issue by leemcd56** [florianv/business#2]
Using the recommended method of installation through composer, the following exception is thrown:

    [InvalidArgumentException]
    Could not find package florianv/business at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

**Comment by mcordingley** [comment]
Looks like it needs to have a release.

**Comment by florianv** [comment]
Hi,

indeed, there is currently no stable release as I want to make sure the API won't change before doing so. You need to use the `dev-master` version. You can add this to your `composer.json`:

```json
{
    "require": {
        "florianv/business": "dev-master"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```
