### ISSUE TITLE
Arithmetic using business hours...

### ISSUE THREAD

**Issue by jeremyswright** [florianv/business#29]
Is there a way for me to use a timestamp and an interval to calculate the end timestamp.

i.e. what time is 6 business hours from 2020-11-12 12:00:00?

I feel like it can maybe achieved using the timeline but can't work out how to do it...

Thanks.

**Comment by jeremyswright** [comment]
So I think I managed to solve this one. In the timeline the first element is the start time, the 2nd is the next time after the interval, etc.. all the way to the end time.

This seems to work in all the tests I've run.

```
		try {
			$timeline = $this->business->timeline($start, $end, $interval);
		} catch (\Throwable $th) {
			$message = "exception creating timeline: " . $th->getMessage();
			Log::error(basename(__FILE__, '.php') . '->' . __FUNCTION__ . ': ' . $message);

			throw $th;
		}

		if (isset($timeline[1])) {
			return new Carbon($timeline[1]);
		} else {
			return $start;
		}`

**Comment by jeremyswright** [comment]
Actually, this no longer seems to be working.

```
$this->days = [
	new Day(Days::MONDAY, [['09:00', '17:00']]),
	new Day(Days::TUESDAY, [['09:00', '17:00']]),
	new Day(Days::WEDNESDAY, [['09:00', '17:00']]),
	new Day(Days::THURSDAY, [['09:00', '17:00']]),
	new Day(Days::FRIDAY, [['09:00', '17:00']]),
];

$this->business = new Business($this->days);

$timeline = $this->business->timeline(
	Carbon::createFromFormat('Y-m-d H:i:s', '2020-11-30 16:32:17'),
	Carbon::createFromFormat('Y-m-d H:i:s', '2020-12-03 17:00:00'),
	CarbonInterval::minutes(16)
);

$timeline: [
	"2020-11-30T16:32:17.000000Z",
	"2020-11-30T16:48:17.000000Z",
	"2020-12-01T09:00:00.000000Z",
	"2020-12-01T09:16:00.000000Z",
        ...
]
```
That 3rd element in the timeline isn't correct. It should be `2020-12-01T09:04:17.000000Z`, no? It happens further down the timeline array each time the date changes (which I've edited for brevity).

**Comment by jeremyswright** [comment]
I ended up writing something bespoke to solve my requirement.

**Comment by florianv** [comment]
@jeremyswright Sorry for the delay.

Once the closing time for a day is reached, it moves to the next day at opening time.

So, I think the 3rd element is correct, since it reopens the next day at `09:00`.
