### ISSUE TITLE
Prefer modern DateTime implementations

### ISSUE THREAD

**Issue by rvanvelzen** [florianv/business#3]
Specifically: `DateTimeInterface` and `DateTimeImmutable`.

Of course, feel free to close if you strictly target PHP 5.4 or lower. :-)

(Edit: `DateTimeInterface` and consorts were introduced in 5.5, not 5.4)

**Comment by florianv** [comment]
Hi, thanks for the suggestion. 

I thought about it too but the first version will target PHP 5.4 so we can't rely on these classes.
