### ISSUE TITLE
Feature request: serialize/deserialize

### ISSUE THREAD

**Issue by olimsaidov** [florianv/business#5]
Please, add serialization methods for Bussiness class

**Comment by florianv** [comment]
Hi @olimsaidov, what's your use case for adding this feature ?

**Comment by olimsaidov** [comment]
Want to persist created instances to database and restore them for later
use.

**Comment by florianv** [comment]
Thanks for the suggestion, I added the feature in the latest version (1.1.0), you can run `composer update` to get it.

I also added some documentation about it https://github.com/florianv/business#serialization.

**Comment by olimsaidov** [comment]
Great work. Thanks

**Comment by florianv** [comment]
Np, thanks :)
